
#==================== spring Setting =====================#
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  datasource:
    driver-Class-Name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/db_lht?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp


server:
  port: 8081